//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuong.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDong
    {
        public int MaHopDong { get; set; }
        public Nullable<System.DateTime> NgayKy { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<bool> TinhTrang { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> LoaiHopDong { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        private string tenLoaiHopDong;

        public virtual ChucVu ChucVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }

        public string TenLoaiHopDong
        {
            get
            {
                return LoaiHopDong == QuanLyLuong.Constants.LoaiHopDong.HOP_DONG_CO_THOI_HAN ? "Có thời hạn" : "Không thời hạn";
            }

            set
            {
                tenLoaiHopDong = value;
            }
        }
    }
}
