//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuong.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhenThuong
    {
        public int MaKhenThuong { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> NgayKhenThuong { get; set; }
        public Nullable<double> TienThuong { get; set; }
        public string LyDo { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        private string maKhenThuongAsString;
        public string MaKhenThuongAsString
        {
            get
            {
                return "KT" + MaKhenThuong;
            }

            set
            {
                maKhenThuongAsString = value;
            }
        }

        public string HinhThuc { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
