//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuong.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class LuongNhanVien
    {
        public int MaLNV { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<double> LuongCoBan { get; set; }
        public Nullable<double> Thuong { get; set; }
        public Nullable<double> KyLuat { get; set; }
        public Nullable<double> LuongTDNN { get; set; }
        public Nullable<double> LuongTDHV { get; set; }
        public Nullable<double> HSPCChucVu { get; set; }
        public Nullable<double> NghiViec { get; set; }
        public Nullable<double> DieuChinh { get; set; }
        public Nullable<double> Thue { get; set; }
        public Nullable<double> LuongThucLinh { get; set; }
        public Nullable<System.DateTime> NgayBatDau { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
        public Nullable<System.DateTime> NgayTraLuong { get; set; }
        public Nullable<int> TamUng { get; set; }
        public Nullable<double> LuongThamNien { get; set; }
        public Nullable<double> PhatNghiViec { get; set; }
        public Nullable<double> LuongChucVu { get; set; }
        public Nullable<double> TienBaoHiem { get; set; }
        public Nullable<double> SoNgayLamViec { get; set; }
        public Nullable<double> SoNgayTangCa { get; set; }
        public Nullable<double> LuongLamViec { get; set; }
        public Nullable<double> LuongTangCa { get; set; }
        public Nullable<int> SoLanDiMuonVeSom { get; set; }
        public Nullable<double> PhatDiMuonVeSom { get; set; }
        public Nullable<int> SoNgayNghi { get; set; }
        public Nullable<double> PhiCongDoan { get; set; }
        public Nullable<double> LuongSauThue { get; set; }
        public Nullable<bool> ThuViec { get; set; }

        public virtual NhanVien NhanVien { get; set; }
    }
}
