//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuong.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NghiViec
    {
        public int MaNghiViec { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
    }
}
