//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuong.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhanVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhanVien()
        {
            this.ChamCongs = new HashSet<ChamCong>();
            this.HopDongs = new HashSet<HopDong>();
            this.KhenThuongs = new HashSet<KhenThuong>();
            this.KyLuats = new HashSet<KyLuat>();
            this.LuongNhanViens = new HashSet<LuongNhanVien>();
            this.NghiViecs = new HashSet<NghiViec>();
            this.QuaTrinhCongTacs = new HashSet<QuaTrinhCongTac>();
            this.QuaTrinhLuongs = new HashSet<QuaTrinhLuong>();
        }
        public string MaNhanVienAsString
        {
            get
            {
                return "MJC" + MaNhanVien;
            }

            set
            {
                maNhanVienAsString = value;
            }
        }
        private string maNhanVienAsString;
        public int MaNhanVien { get; set; }
        public string HoTen { get; set; }
        public string HinhAnh { get; set; }
        public string GioiTinh { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string CMTND { get; set; }
        public string DanToc { get; set; }
        public string TonGiao { get; set; }
        
        
        public string DienThoai { get; set; }
        public string Email { get; set; }
        public string QuocTich { get; set; }
        public string QueQuan { get; set; }

        public string TinhTrangHonNhan { get; set; }
        public string ThanhPhanXuatThan { get; set; }
        public string NangKhieu { get; set; }
        public string TinhTrangSucKhoe { get; set; }
        public string BoPhan { get; set; }
        public string SoQD { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaTrinhDoHocVan { get; set; }
        public Nullable<int> MaTrinhDoNgoaiNgu { get; set; }
        public string TinhTrang { get; set; }
        public Nullable<System.DateTime> NgayVaoLam { get; set; }
        public Nullable<int> MaBacLuong { get; set; }

        

    
        public virtual BacLuong BacLuong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChamCong> ChamCongs { get; set; }
        public virtual ChucVu ChucVu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HopDong> HopDongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhenThuong> KhenThuongs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KyLuat> KyLuats { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LuongNhanVien> LuongNhanViens { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NghiViec> NghiViecs { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
        public virtual TrinhDoNgoaiNgu TrinhDoNgoaiNgu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhCongTac> QuaTrinhCongTacs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuaTrinhLuong> QuaTrinhLuongs { get; set; }
        public virtual TaiKhoan TaiKhoan { get; set; }
    }
}
