//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyLuong.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuaTrinhCongTac
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
        public Nullable<int> MaNhanVien { get; set; }
        public Nullable<int> MaChucVu { get; set; }
        public Nullable<int> MaPhongBan { get; set; }
        public Nullable<int> MaTrinhDoHocVan { get; set; }
        public Nullable<int> MaTrinhDoNgoaiNgu { get; set; }
        public Nullable<System.DateTime> NgayKetThuc { get; set; }
    
        public virtual ChucVu ChucVu { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual PhongBan PhongBan { get; set; }
        public virtual TrinhDoHocVan TrinhDoHocVan { get; set; }
        public virtual TrinhDoNgoaiNgu TrinhDoNgoaiNgu { get; set; }
    }
}
